### ISSUE TITLE
Small change to README

### ISSUE THREAD

**Issue by namloc2001** [avishayil/caponeme#10]
Hi,

Just a very minor point, but you may wish to amend the second bullet point so that it doesn't include the IAM role name from your scenario (i.e. make it clear to user where to insert their IAM role name into the URL) such as:

## Discovering the contents of the S3 Bucket
- On the web application, type the following to get the IAM role name: http://169.254.169.254/latest/meta-data/iam/security-credentials
- Using the IAM role name you got on the previous step, discover the AWS credentials http://169.254.169.254/latest/meta-data/iam/security-credentials/[IAMRoleName]

Regards, Matt

**Comment by avishayil** [comment]
Thanks @namloc2001 , that's a good suggestion.
Changed on https://github.com/avishayil/caponeme/commit/526e600164b210e4dca0c238e435bd4c2e7b1a66
