### ISSUE TITLE
README amendment?

### ISSUE THREAD

**Issue by namloc2001** [avishayil/caponeme#11]
Hi,

Under mitigation 1: I was doing this mock using my Windows laptop and used internet browser to access the vulnerable app. Is this what the "Now switch to the "hacked" shell is referring to. Could/should it say "Now using your browser"?

Also, "Now switch to the "hacked" shell and try to run the vunlerable web application. What happens?" -> vulnerable is misspelled.

Regards, Matt

**Comment by avishayil** [comment]
Thanks @namloc2001 , you're really doing some effort here.
Fixed by https://github.com/avishayil/caponeme/commit/526e600164b210e4dca0c238e435bd4c2e7b1a66
