### ISSUE TITLE
SSRFInstance: CREATE_FAILED

### ISSUE THREAD

**Issue by namloc2001** [avishayil/caponeme#7]
Hi, I've just tried running the CloudFormation template. It got stuck on SSRFInstance creation for 20 minutes before telling me "In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=c1jifmii8vw5xd0npsnf9eza9"

Could you please include these steps:

## Getting Started
- Make sure you have the latest version of `awscli` installed on your terminal.
- Make sure you run this from the `us-east-1` (North Virginia) region on the AWS Console.
- Visit https://aws.amazon.com/marketplace/pp/B072JNJZ5C/ click on "Continue to Subscribe" and then click on "Accept Terms".

Thanks, Matt

**Comment by avishayil** [comment]
Thanks @namloc2001 , I added this information on https://github.com/avishayil/caponeme/commit/955b9d180199dc9e1cdefddab6f22a54b031340f
