### ISSUE TITLE
Strange issue with Windows 10 Firefox

### ISSUE THREAD

**Issue by namloc2001** [avishayil/caponeme#8]
Hi, when I first loaded the web URL using Firefox it loaded a webpage with 4 buttons and references to Bitnami. It wasn't the "Server Side Request Forgery" page. I discovered what the page should be when I opened it in Chrome. Since doing this, it has now loaded correctly in Firefox.

It had left me puzzled as to how to complete the rest of the exercise because the "Submit Query" form wasn't showing. I wonder if it's worth including a screenshot of the page the user should expect to see in the README. Something like:

## This is the page you should expect to see:
![image](https://user-images.githubusercontent.com/30868661/71972441-89b7bf00-3204-11ea-9a96-73fd7b8a9036.png)

**Comment by avishayil** [comment]
Thanks @namloc2001 , this is noted now on https://github.com/avishayil/caponeme/commit/955b9d180199dc9e1cdefddab6f22a54b031340f
