### ISSUE TITLE
Update README for Windows users

### ISSUE THREAD

**Issue by namloc2001** [avishayil/caponeme#9]
Hi, could you please update the README, in the Discovering the contents of the S3 Bucket section:

- If using Linux, type the following on your terminal to impersonate the IAM role

```
export AWS_ACCESS_KEY_ID="<access_key_id>"
export AWS_SECRET_ACCESS_KEY="<secret_access_key>"
export AWS_SESSION_TOKEN="<session_token>"
```

- If using Windows, type the following on your terminal to impersonate the IAM role

```
set AWS_ACCESS_KEY_ID=<access_key_id>
set AWS_SECRET_ACCESS_KEY=<secret_access_key>
set AWS_SESSION_TOKEN=<session_token>
```

(**Note:** Do not include quotes when setting Windows env variables.)

**Comment by avishayil** [comment]
Thanks @namloc2001 , fixed on https://github.com/avishayil/caponeme/commit/955b9d180199dc9e1cdefddab6f22a54b031340f
